### PR TITLE
New Page: List of all Students added

### PR DESCRIPTION
**Pull request by harikishantk**
To Do:

- [x] Create an empty HTML page displayed at /students/ endpoint.
- [x] Fetch student data from database and display in form of cards.
- [x] Add filter to filter the students section-wise.

I had uploaded video and some screenshots regarding the functionality of the page.

Since the video recorded in Win+Alt+R, the dropdown menu is not visible. So I'm requesting you test the functionality in your workspace.

# Video
https://user-images.githubusercontent.com/58771359/107112623-050ff800-687f-11eb-94b9-ff1c838bd438.mp4

# Screenshots
image

image

### CODE REVIEW

**Comment by garg3133** [comment]
Can you resolve the conflicts in requirements.txt file? Also, don't push the `sample-db.sqlite3` file.

**Comment by harikishantk** [comment]
Sure

**Comment by harikishantk** [comment]
I had removed `sample-db.sqlite3` file and made changes in `requirements.txt` as per the `garg3133:master`. Still, it's showing out conflicts.

**Comment by garg3133** [comment]
Follow these instructions:
* First create a new branch out of your current branch (`git checkout -b <new-branch-name> class-dropdown done`) so that this branch remains safe.
* In the new branch, remove the last commit. `git reset --hard HEAD^`
* Squash all other commits into one commit:
  * `git rebase -i HEAD~9` (because you made 9 commits)
  * In the file opened, except for the first `pick`, relace all `pick` with `squash`.
  * Save the file and close it.
  * An another file will open asking you the commit message after merging all commits into one. Remove all existing commit messages and add a new single commit message.
  * Save this file and close it.
* Now soft reset your commit thus created. `git reset --soft HEAD^`
* Remove `sample-db.sqlite3` from the staging area and commit rest of the files (with the same commit message as entered above).
* Rebase your branch with upstream master. `git pull --rebase upstream master`.
* Resolve merge conflicts in `requirements.txt` when asked to.
* Create a new PR from your new branch.

**Pull request closed without merging**
