### PR TITLE
Add Email Verifier #57

### PR DESCRIPTION
**Pull request by raman08**
Updated the HTML so that only proper mail can signup or signing
Issue: #57

### CODE REVIEW

**Comment by garg3133** [comment]
Hey, your regex is not working on any email address I tried (not even gmail ones).

**Comment by raman08** [comment]
Can you tell me that's the exact problem is?
I mean is is not verifying your email or it verify every mail?

Because for me it's working

**Comment by garg3133** [comment]
Screenshot from 2021-01-17 01-00-36

**Comment by raman08** [comment]
Oh ok, I will check it soon and report back to you.

**Pull request closed without merging**
