### PR TITLE
scrollbar in capture page

### PR DESCRIPTION
**Pull request by kumarishalini6**
# Related Issue
Fixes: #270 

I have made scrollbar button in capture page and improve side scrollbar.

### CODE REVIEW

**Comment by garg3133** [comment]
@kumarishalini6 The captures page was recently moved to the `event` app, so can you maybe resolve the conflicts in this PR?

**Comment by kumarishalini6** [comment]
Ok

**Comment by kumarishalini6** [comment]
done

**Review by garg3133 — COMMENTED** [review]
@kumarishalini6 You've added the button to an older version of the file. Try pulling in the latest changes and then adding the button.

Also, I think instead of writing the same code for all the pages, we should write the component only once (in `templates/globals/scroll_to_top` folder and then use it in our project using the `include` template tag. Remember to put the CSS and JS in separate files while doing so and then including them in the scrollToTop template using `link` and `script` tag.

**Comment by garg3133** [comment]
@kumarishalini6 Can you please remove the home/captures.html page from this PR?

**Comment by kumarishalini6** [comment]
Done

**Comment by kumarishalini6** [comment]
@garg3133 can you please review this PR also

**Comment by kumarishalini6** [comment]
@garg3133  can you please review this PR

**Comment by garg3133** [comment]
Looks good now, merging it into master.

Thanks, @kumarishalini6 for your contribution.

**Pull request merged**
