### PR TITLE
Fixed new home mobile view

### PR DESCRIPTION
**Pull request by tanishq-arya**
# Related Issue
Fixes: #229 
fixed spacing in new home mobile

# Prosposed Changes
- Added media queried for html and body
- There was duplicate CSS for a button so I removed that.

# Additional Info
- any additional information or context

# Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **
Screenshot (1168)
Screenshot (1166)
Screenshot (1167)

### CODE REVIEW

**Comment by garg3133** [comment]
@tanishq-arya While this seemingly solves the issue, it is more of a workaround than an actual solution.

On inspecting it myself, something in the contact us section is causing this behaviour, so you may want to look into that. As some work on the contact us form is still going on in #225, you might need to wait for sometime till that is merged.

**Comment by tanishq-arya** [comment]
> @tanishq-arya While this seemingly solves the issue, it is more of a workaround than an actual solution.
> 
> On inspecting it myself, something in the contact us section is causing this behaviour, so you may want to look into that. As some work on the contact us form is still going on in #225, you might need to wait for sometime till that is merged.

I already looked at everything, but I'll keep on this till the work is being done on contact section.

**Comment by tanishq-arya** [comment]
@garg3133 I found the flaw. The mx auto class was causing the contact us forms to overflow. I removed it and modified the containerly class with margin: 0 auto; to center the forms.

**Comment by garg3133** [comment]
> The mx auto class was causing the contact us forms to overflow. I removed it and modified the containerly class with margin: 0 auto; to center the forms.

It still doesn't seem to fix the flaw.

Anyways, it was fixed in #225 itself (was caused due to the animation of the email in the contact us form). Closing this PR and corresponding issue.

**Pull request closed without merging**
