### PR TITLE
Corrected pep-8 warnings

### LINKED ISSUE #105: Refactor the Errors observed in Flake8 linter
I ran the Flake8 linter on the whole codebase.

Here is the [instance](https://github.com/garg3133/JagratiWebApp/pull/104/checks?check_run_id=1888095595).

There are approximately 50 errors.

I believe we should start sorting them like right now before the numbers start piling up.

Moreover, we need to consider that flake8 is a compromising linter unlike PyLint, I understand that the errors *might* not be breaking, but I believe it's always a good idea to get rid of them.

### PR DESCRIPTION
**Pull request by vybhav72954**
Dear maintainers, 

As pointed out by you, I removed all the previous discrepancies that I introduced in the closed or #107

This time the warnings I have dealt with are of missing/extra white spaces, long lines etc.

Resolves #105

### CODE REVIEW

**Comment by vybhav72954** [comment]
So there are still some errors according to the Linter action.

This corresponds to 4 things.

- According to the Linter there are unused imports (I decide not to touch them as I have no exact idea of the working of the project)
- Star Imports. (Honestly, star imports are never a good idea, so I would request maintainers to solve them if possible) [Further reading](https://stackoverflow.com/questions/2360724/what-exactly-does-import-import)
- Some functions are too complex. [Further reading](https://www.flake8rules.com/rules/C901.html#:~:text=Functions%20that%20are%20deemed%20too,else%20and%20for%20%2F%20while%20loops.)
- There are a few unused variables. ```apps/feedbacks/views.py:9:5: F841 local variable 'submitted' is assigned to but never used```
- In `home/views.py` there is a POST request which is too long according to pep-8 guideline.

I think admins can solve these errors only, so I leave this to you guys.

**Comment by garg3133** [comment]
Sorry @vybhav72954 but I don't think I'll be able to review your PR on such short notice. This PR affects a large part of the codebase and I cannot just merge it without being assured that the changes do not break anything.

Also, how can you expect a maintainer to review your PR as soon as you open one? No one is committed full time on a project and may be busy somewhere else. Have patience, buddy. Patience is of utmost importance while being involved in Open Source Communities.

Also, spamming the admins everywhere won't do any good in getting your PR merged. Everyone understands that it takes time to review a PR (especially when it's this long and affects such a large part of the codebase).

**Comment by vybhav72954** [comment]
Sure thing, only if its possible for you to review 😄

**Comment by garg3133** [comment]
@vybhav72954 I'm not very sure about these changes. There are many things in these changes that we want to keep and many which we don't want to keep. And with all the changes in just 2 commits, it will be very hard for me to review and for you as well to make the changes. So, I guess, I'll be correcting all these things myself.

Thank you so much for your time and your PR. Wish you all the best!

**Pull request closed without merging**
