### PR TITLE
Fixed Jagrati Tagline

### PR DESCRIPTION
**Pull request by adenashameem**

### CODE REVIEW

**Comment by garg3133** [comment]
Changes looks good to me. Thanks @adenashameem!

Just a few suggestions:
- After you PR completely fixes an issue, you should always mention `Fixes: <issue_id>` in the PR description. Doing this automatically closes the issue on merging the PR. Also, referencing issue like this in PR lets the people know (when they visit the issue) that someone else is working on this issue and his/her PR is currently open and under review.
- Even if your PR does not solve the issue completely but a part of it, you can mention `Part of: <issue_id>` in the PR description. Doing so does not closes the issue upon merging PR but still does the second job as mentioned above.
- While working on an issue or implementing a new feature, always first create a new branch and then start working. Never make your changes directly onto the master branch as master branch should always be clean and in sync with the original repository. This helps a lot if you accidently mess things up or want to work on different issues at the same time.

Merging this PR and wish you many such more good PRs :)

**Comment by adenashameem** [comment]
Thankyou for these suggestions @garg3133 
Regarding the third point, I did create a new branch in my local repository, made changes to it and then merged that branch to my local repository's master branch. And then compared your master and my local master and sent a pull request. Isn't this process okay or should compare my newly created branch(not master) and the original master when making a pull request ?

Since I'm relatively new to Open Source, will be really helpful if you could clear this doubt. Thanks.

**Comment by garg3133** [comment]
@adenashameem You can do so if you are working on your own project and are sure that your changes will surely get merged with the main repo immediately. But if you are contributing to some other repository, this is not the right approach as I've said earlier that your local master branch should always be in sync with the main repo's master branch. Since you have created a new commit in your local master branch, it got out-of-sync with the main repo's master. And now, if you want to continue working on some other issue while your PR is in review, you won't be able to do so as on creating a new branch, that commit will also appear in your new branch (and it is not present in the main repo yet).

So, always create the PR from the branch you created and not the master branch.

Hope this clarifies your doubt.

**Comment by adenashameem** [comment]
Thanks alot @garg3133.

**Pull request merged**
