### PR TITLE
Added github action

### PR DESCRIPTION
**Pull request by Aayush-hub**
Added Github Action/Welcome Bot for first time contributors to this project.
Fixes: #56 #86

### CODE REVIEW

**Comment by Aayush-hub** [comment]
@garg3133 Contributed for #SWOC21 #mexili

**Comment by garg3133** [comment]
Hey @Aayush-hub, thanks for the PR! Merged into master.

BTW, you should never create a PR from the master branch.

**Comment by Aayush-hub** [comment]
@garg3133  Thanx , will take take of it next time. Looking forward for more contributions.

**Comment by garg3133** [comment]
@Aayush-hub The Github action you added is not working properly.

See https://github.com/garg3133/JagratiWebApp/pull/89/checks?check_run_id=1840797860

Have you tried this in some other repository?

**Comment by Aayush-hub** [comment]
@garg3133 Yes, I have applied it to many repositories, and it works fine. In https://github.com/garg3133/JagratiWebApp/pull/89/checks?check_run_id=1840797860  the bot is working fine and there is an issue from contributor's side. The contributor can try re-commiting the change it will work fine.

**Comment by garg3133** [comment]
@Aayush-hub I don't think there's any problem on the contributor's side. In fact, many other people were facing the same issue. See https://github.com/actions/first-interaction/issues/10. Also, there were some deprecated methods being used in the action which I guess is coming from using `github.Github()` instead of `github.getOctokit()`.

Anyways, I created an action of my own (https://github.com/garg3133/welcome-new-contributors) which should fix all the issues with this action (as this action is not maintained properly). I've kept the structure of the workflow file same for now but soon I'll be adding a feature of using your own bot account instead of `github-actions` bot.

**Pull request merged**
