### PR TITLE
Updated README.md by adding OSS events

### LINKED ISSUE #114: README.md file enhancement
The README.md file can be enhanced by adding a list of all the open source programs that this project has been listed in. A table of all the contributors will further enhance the file.

### PR DESCRIPTION
**Pull request by vismitap**
Fixed #114

# Related Issue
Fixes: #114 

# Prosposed Changes
- Add the following OSS events in README.md
* Kharagpur Winter of Code 2020
* Script Winter of Code 2021
* Mexili Winter of Code 2021
* GirlScript Summer of Code 2021

# Screenshots
image
image
image
image

### CODE REVIEW

**Comment by garg3133** [comment]
@vismitap The title and the initial section looks good but we don't want this section to be so big in Readme, but just a list of all the programs in the form of a table, with an image of the program (all program images should be of same size), the program name and the year in which we were a part of that program.

Also, it would be better if this section is below the "How to contribute" section.

**Comment by vismitap** [comment]
> @vismitap The title and the initial section looks good but we don't want this section to be so big in Readme, but just a list of all the programs in the form of a table, with an image of the program (all program images should be of same size), the program name and the year in which we were a part of that program.
> 
> Also, it would be better if this section is below the "How to contribute" section.

I will make the changes soon!👍

**Comment by vismitap** [comment]
@garg3133 Is this what is expected? Any more changes? I think How to contribute should be below the table to make it look good. What do you say?

image
image

**Comment by garg3133** [comment]
No, I mean like the table in Project Maintainer section of this PR #138.

**Comment by vismitap** [comment]
> No, I mean like the table in Project Maintainer section of this PR #138.

Okay got it! Will do the changes. Do you want the project maintainer and contributors section too?

**Comment by garg3133** [comment]
> > No, I mean like the table in Project Maintainer section of this PR #138.
> 
> Okay got it! Will do the changes. Do you want the project maintainer and contributors section too?

Yeah, you can add them.

**Comment by vismitap** [comment]
This is how it looks now:
image
image

**Comment by garg3133** [comment]
These starts that you added in every heading looks a bit weird, leave it as before.

For the table, can you put the year in a separate like (like the table in Project maintainer section). Also, use better quality images for the programs, like for SWOC, [this](data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBw8HBhUPBxIVFhAVGBMYFxUVGRcfHxkVGhYgIhkWGhsdHighHiYnJxUWIT0hJSk3Mi4vGB8zOzMsOCguLjcBCgoKDg0OFxAQGCsdHR83LTctKzctLS0tKystLS0rLS0tLS0rLTctLSstKy0tKystOCsrNy03LSstLS03LS0tK//AABEIAMgAyAMBIgACEQEDEQH/xAAcAAEAAgIDAQAAAAAAAAAAAAAABgcEBQEDCAL/xAA6EAACAQMCAgcGAwcFAQAAAAAAAQIDBBEFBhIxByEiQVFhgRMUQlJxoSMyU0NikZKxwdFjwtLh8DP/xAAYAQEAAwEAAAAAAAAAAAAAAAAAAQIDBP/EAB4RAQADAAMBAQEBAAAAAAAAAAABAhEDITESIhNR/9oADAMBAAIRAxEAPwC8QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcECl0gujrsqV3SSoRnKDks8Sw8cT/hy/qWrS1vFZtFfU+BjVr6lRsXXqziqKjxObfVw4znJWWl9Lj1PeELW2t17rUqKnGeXx9bwp45Y78eHeIrMk2iFrAAqsAAAAAAAAAAAAAAAAAAAAYuoX9HTbZ1b+pCnBc5TaS+4GSG8LrKu3J0y2lnmGhU3Xn88sxh/yl9vqVbuHempblnw3taXA+VKn2Y/ThXXL1ya14bT70ztyRD0RQ3XY3WtKys68aldqT4YdaSisvMl1emTc1JqnDNRpLxZSHQ9tS/tNyQvLyhOnQUKi4p4i25RwsRfa+xcWs2bvLPhpvrTyl4+X3ItWItmprMzGs2nNVIZptNPvRCd/bWV5Rld2KSqxWZx+eKX5vqkvUy9J1GWn1uCtngb614PxK86XN/u9qS07R5YpJ4rVF8b/TXku/x+nO9K2rfpW0xNe0N1zdNxe6crGjUfusZZ4fmf+M9ePHrLZ6KNgrQrdXuqxTu5rsRf7KD/ANzXPw5eJBdE6PLqjoC1G6j1/mVLHajT/Uf+O5df0nWxd4K2pq11aWIJdio/hXyS8vA25Im1ZmrOkxE9rCvLqnZWzq3clCnHrcpPCR16dqNHU7b2thUjOHLii+9dxS++N11N0agqNgpe7xliEFzqS5cTXr1Isro+25Pbui8N0/xaj45xXKLxhR8/N/4Oe3H812fWtb7OR4k0ailJqLWVjK8Pqdh5+6WtQuNK6RJVdPqTpz9nSxKDaz2fujN230zXNriGv01Wj+pDEZ+q/LL0wP4zMbCf6RuSvQ4I/t3een7iSWm14+0f7OfZn/K+fpkkBlMTHq265AASAAAAAAAAAAAVT0/W86uj286cZOMZ1OJpNqOYrGX3FrHy0pLDLVt8zqLRsPImmVKFK9i9ThOdLvjTmot+ri//AHeXjsXce3KMVHSowtqv+ssS6/8AVk3n+Y225OjHTNczKFP2FV/HR6lnzh+V/Z+ZVe5OifUdIzKySuaS76f5sedN9fpHJ0TavJ7OMfm1XoeE1UgnTaafJo+zz70L3dxb70VtOdSNNxq8VJuSXEo98eWSyelrc1fbe3U9NTVStJwVT5FjLa8/D1MbceW+WkW2NareG9LG03RG1i8y61VqJ9mE/hi/Pxfd/HHzb7asLzctO71GGXHmvhlL4JTXfjH9MkL6Lthy3Ld+96sn7pCXJ/tp+H0zzfp44uLW9IUIe0s4pJc4pcku9I12I/OqZM9t/JrhzLl/Yoncd3aVtfqLR/8A5Z6n3OXxcPl4Gw3fvKrUsnYWUuxynNc2v00/Dxfobbo32QpQV7rMMpr8KnJdz+OS/on9fAtxx/KJtZW8/fUMboxo2dLXHK6X47X4Wfyr5sfvf9ltlRby2zLQbr21ln2En2WudOXyt/0ZPNkavU1nRFO7XbjJwcvmwl2vv9ivPWLfuJ6W4pz8y2+oadQ1O39nqFKFSHyzimvuVvu3os0qFB1qNf3PznJOnn6Tef4SNf0q7+1DRtelZaVKNOCjB8ainJ8Sy+uWUvRFa2ljqO7r7NCNa4qd8pNvH1lLqj6sjjpbN3E3tHmMDUraFjfOFrWhVjF9VSmppP8AmSZd/Qdq9zqmkV46jVnUVOcFDjeWk4vKzz7jS7b6FpSxPcdbC/So8/Wb/svUtPQtAtdv2nstIpRpxfW8Zbk/GUn1snl5KzGQilZ3W0ABzNgAAAAAAAAAAAAAAAGJPT6E76NeVOHtoppVOFcSTWGuLng+r2yo6hbunfU4VKb5xnFNfwZkgDqo0Y0KShQiowSwoxSSS8EkV70lb09yhKy0qX4rWKk18CfwL95/b68rGIFddGtG73HK6uKrdGc3OVLh6228uPFnlnPd/k045rE7ZS+5kIXtLaVS6tle3sPwE+yn8X7zXgWroWqe1SpXD7S/K/Hy+puYUowpKEUlFLCil1Y8MGmegcF8p0pYgmnjvXkWtyffqIp8+NzWpRrU3GqlKL5prKfocUaMaFNRoRUYrkorCXojtBi0RTU9g2Gr7glfarGVSbUEoN4guFY5Lrfq8EktbanZ0FTtIRhBcoxSSX0SO4EzMoyHIAISAAAAAAAAAAAAAAAAAAAAAIJubd11abjlZaX7pT4KcKkql5UcVLi5KGMcsG4sdxK2t4U9elTV06NWvL2CnKm6UJPtRk+fVw9X1MHeOkXmp30fcrTT61OMfzXak5KTbylhcuRH47C1DTtNorTalGdVULmhUjNzUYwrybzTeM9nPf4GmVmIU7iUyW7rHhTnV4Yu3VzmUZJewbwpfXLXVzOjSd82GpufBOVN04Oq1WhKGaS/aRzzRFKHR9e39hUpazUowcbWla0XS4nlU6qnGpPPnBLHmzMvdnahuarOe5Z0KbjQnRpKhxPMpNN1J57uyuyPmv8Aptkl2/u+z3BcunYOopqPGlUpyjxU84445XWutEgI1tijqtKrjXlbKlCnGEfY8blKS+Jt4SWO7zJKUtm9LQAAhIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//9k=) image can be used. For KWoC too, please use a better image (current image looks more towads left).

**Comment by vismitap** [comment]
<table>
  <tbody>
  <tr>
    <td align="center"><a href="https://kwoc.kossiitkgp.org/">
    <br><sub><b>Kharagpur Winter of Code</b></sub><br>2020</a>
    </td>
    <td align="center"><a href="https://swoc.tech/">
    <br><sub><b> Script Winter of Code</b></sub><br>2020</a>
    </td>
    <td align="center"><a href="https://mexili.github.io/winter_of_code/#/">
    <br><sub><b> Mexili Winter of Code</b></sub><br>2021</a>
    </td>
    <td align="center"><a href="https://gssoc.girlscript.tech/">
    <br><sub><b> Girlscript Summer of Code</b></sub><br>2021</a>
    </td>
  </tr>
</tbody></table>

**Comment by garg3133** [comment]
Looks good @vismitap, merged into master!

Sorry for the delay and thanks for your contribution 🚀

**Pull request merged**
