### PR TITLE
Sk1122 pass reset

### PR DESCRIPTION
**Pull request by sk1122**
# Related Issue
Fixes: #182 

# Prosposed Changes
- Improved Password Reset Confirm Page
- Changed The Design to a sleeker and Simple one with enough margin and padding around it

# Additional Info

# Screenshots

jagraticonfirm

### CODE REVIEW

**Comment by garg3133** [comment]
@sk1122 The design should be consistent with all other pages. Please look at other similar pages, like `Change Password`, etc. for reference.

Also, your PR seems to have some merge conflicts, can you fix these?

**Comment by garg3133** [comment]
Also, this PR contains some commits from your last PR (it seems like you didn't created this branch from `master` branch).

You should go to `master` branch, pull the recent changes and then create a new branch from there and then make the required changes.

**Comment by sk1122** [comment]
Ya Okay @garg3133

**Comment by sk1122** [comment]
Hello @garg3133 ,
Please Look at these pictures

### Password Change Form

Password_change

### Forgot Password Page

Password_reset

As you can see Forgot Password is looking much cleaner because it is centered on the page. If we change Password Change to Center Aligned form, it will look much cleaner and good.

**Comment by garg3133** [comment]
@sk1122 I think you're looking at the older version of "Change Password" page. You should update your fork first as I already mentioned before:
> You should go to `master` branch, pull the recent changes and then create a new branch from there and then make the required changes.

**Comment by sk1122** [comment]
Opened a New Pull Request with Changed Design and Commit History.

Sorry for not checking before committing and sending screenshots

**Pull request closed without merging**
