### PR TITLE
Added team page

### PR DESCRIPTION
**Pull request by fatma-sia27**
Fixes: #218 

Hey as assigned isssue#218 , I had created an team page for the website . Please review it .
Thank you.

### CODE REVIEW

**Comment by fatma-sia27** [comment]
@garg3133 , please review this PR.
Thank you

**Comment by fatma-sia27** [comment]
@garg3133 please review my pr , gssoc period is about to end plss review it🙏🙏

**Review by garg3133 — COMMENTED** [review]
@fatma-sia27 Really sorry for the delay. I was away from keyboard for the last few weeks due to some COVID emergency in my family.

Taking a look at your PR, while the page you designed looks really pleasing as a standalone page, it does not quite match with the overall theme of the site (no header, footer among other things). And the side banner containing the logo is taking too much width the adding more contributors to the list is going to make the page too long (maybe having that banner at the top would be better).

But these are kind of secondary issues, the primary issue here is that you cannot access this page from the django app, it is a standalone page. You should first integrate this page with the Django app (See other pages, how they are written).
* Extend this page to `base.html`.
* Keep all the images and CSS/JS files in the `static` directory (you've copied the images to the `templates` directory) and reference them using `{% static 'path-with-respect-to-static-directory' %}`.
* Remove all the unnecessary files (like the `contact.us1.html`).
* Create a new URL endpoint for team in `home/urls.py` and the corresponding view in `home/views.py` which will be used to render the page you just created.

**Comment by fatma-sia27** [comment]
Hey @garg3133 , inside status directory there are many folders like accounts, global, home, new_home, logo etc. So in which folder should I put my html and css files?

**Comment by garg3133** [comment]
@fatma-sia27 Inside the home directory.

**Pull request closed without merging**
