### PR TITLE
readme.md update

### PR DESCRIPTION
**Pull request by nilisha-jais**

### CODE REVIEW

**Comment by nilisha-jais** [comment]
Screenshot (7)
Screenshot (11)

**Comment by garg3133** [comment]
Hey @nilisha-jais, thanks for working on this. For the list of programs, can we have the heading like "This project has been a part of:" and then list the different programs in the form of a table, with an image of the program (all program images should be of same size), the program name and the year in which we were a part of that program.

Also, the quality of the image showing all the contributors don't seem good. Can you try using any other application for generating this image?

**Comment by nilisha-jais** [comment]
Alright I'll make the changes

**Comment by garg3133** [comment]
Resolved in #185.

**Pull request closed without merging**
