### PR TITLE
change UI of password reset done

### PR DESCRIPTION
**Pull request by Fairspy**
# Related Issue
Fixes: #182 

# Prosposed Changes
- Changed UI of Password reset done page

# Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
Screen Shot 2021-03-23 at 21 23 14
 |  
Screen Shot 2021-03-23 at 21 25 13

### CODE REVIEW

**Comment by garg3133** [comment]
The design looks good, just the content needs to be changes.

Like the heading can be "Reset link sent"

We've emailed you the instructions to reset your password. If the email address entered by you is registered with us, you should receive them shortly. If you don't, please check your spam folder.

Don't include the line below the Go Back button.

**Comment by Fairspy** [comment]
@garg3133 I have made the requested changes please review them.

**Comment by Fairspy** [comment]
@garg3133 Do I need to change anything else?

**Comment by garg3133** [comment]
Sorry for the delay @Fairspy, will review it today.

**Comment by garg3133** [comment]
Merged, after making a few changes like the class-name of button and using bootstrap classes instead of writing CSS properties, etc.

Thanks @Fairspy for your contribution 🚀

**Pull request merged**
