### PR TITLE
add github-guidelines

### PR DESCRIPTION
**Pull request by khareyash05**
With refernce to issue #139 
Added github-guidelines.md

### CODE REVIEW

**Comment by khareyash05** [comment]
@garg3133 Update the file Have a look!

**Comment by garg3133** [comment]
You haven't actually followed what I asked you to change in the last PR!

For inline-code, use single backticks like this: \`Inline code\`

For multi-line code or single-line code but covering the whole line, use three backticks and put your code in the new line in between the backticks.

Multi-line code:
\`\`\`
$ git config --global user.name "YOUR NAME"
$ git config --global user.email "YOUR EMAIL ADDRESS"
\`\`\`

Single-line code but covering whole line:
\`\`\`
$ git config --global user.name "YOUR NAME"
\`\`\`

**Comment by khareyash05** [comment]
@garg3133 Sorry but the changes i made has shown up in my forked repo. Sharing screenshots with you .These are screenshots of forked repo as u can see in the  link

**Comment by AJAYSHARMA2012** [comment]
@khareyash05 I think, you still need to work on the readability of the file like adding commas etc. where required, and you should not include \ in your branch name. you can refer it for legal branch names https://wincent.com/wiki/Legal_Git_branch_names. Also the changes, which @garg3133 suggested are not visible like in the following screenshots, backticks for Multi-line code are not visible.
Screenshot (264)
Screenshot (265)
Screenshot (266)

**Pull request closed without merging**
