### PR TITLE
Fetching images and display in captures page

### PR DESCRIPTION
**Pull request by coding-geek21**
# Related Issue
Fixes: #238 

# Prosposed Changes
- Moved the captures page from home to events app
- Modified the changes in home page , urls.py and views.py

# Additional Info
- The captures page works fine after placing it in events app

# Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  **
image
**

### CODE REVIEW

**Comment by coding-geek21** [comment]
@garg3133 please review this PR , I will make the next pull request within 2 or 3 days ,

**Comment by garg3133** [comment]
@coding-geek21 I am currently super busy with my college project and assignment submissions followed by my end-sem exams, so I might not be available for a few days. Sorry for the delay.

**Review by garg3133 — COMMENTED** [review]
@coding-geek21 First of all, sorry for such a long delay in reviewing your PR.

Your PR looks good for the most part, there is just a small concern on how you are displaying the images. You are basically running for loop over the complete gallery for each event, which can be really expensive w.r.t. time it will take to run through the complete gallery.

Instead, you can create a dictionary with the event name as key and a list of all the gallery instances for that event as value. You can do so by looping through the gallery queryset only once.

**Comment by garg3133** [comment]
It's fine to have it all in the same PR.

**Comment by coding-geek21** [comment]
> @coding-geek21 First of all, sorry for such a long delay in reviewing your PR.
> 
> Your PR looks good for the most part, there is just a small concern on how you are displaying the images. You are basically running for loop over the complete gallery for each event, which can be really expensive w.r.t. time it will take to run through the complete gallery.
> 
> Instead, you can create a dictionary with the event name as key and a list of all the gallery instances for that event as value. You can do so by looping through the gallery queryset only once.

Ok @garg3133  I will try implementing dictionary instead of looping 

but anyway for fetching the objects which are grouped under Particular event name I have to use loop right ? And I'm not familiar in using dictionary in django but i will try to emplement

**Comment by garg3133** [comment]
Yes, you need to use 2 nested loops, one for looping over events (dictionary keys) and one for looping over the event images (dictionary values). Overall time complexity will be O(n).

For adding values in the dictionary, you can loop over the queryset of gallery images and check if the event for that image is already present in the dictionary. If it is, just append the instance to that key and if not, create a new dictionary entry with event name as key and an empty list as value and then append the gallery instance to that list.

**Comment by coding-geek21** [comment]
@garg3133  I have implemented whatever you said and the code is working fine only thing is image is not displaying 
can you please suggest me how to fix this

image

image

image

**Comment by garg3133** [comment]
@coding-geek21 You are over-complicating things. You can just do:
```python
gallery = Gallery.objects.all()
gallery_dict = {}

for image in gallery:
  if image.event.title not in gallery_dict.keys():
    gallery_dict[image.event.title] = []
  gallery_dict.append(image)
```

**Comment by coding-geek21** [comment]
> @coding-geek21 You are over-complicating things. You can just do:
> 
> ```python
> gallery = Gallery.objects.all()
> gallery_dict = {}
> 
> for image in gallery:
>   if image.event.title not in gallery_dict.keys():
>     gallery_dict[image.event.title] = []
>   gallery_dict[image.event.title].append(image)
> ```

Sorry i made the code complex , this was the first time I was working with queryset so 😅 I wasn't familiar with it , Thanks for guiding me , I made the changes and now the images are displayed in captures page . 
image

**Comment by garg3133** [comment]
Looks good, @coding-geek21! Merged 🎉 

Thanks for working on this!

**Pull request merged**
