### PR TITLE
Password validator added in signup

### PR DESCRIPTION
**Pull request by Ananya9878**
# Related Issue  
Fixed: #58

# Prosposed Changes
- We can implement our own password validator for more strong password/custom password.

# Additional Info

- Currently used django core password validator.

# Screenshots

  Updated
:-------------------------:
 ** updated screenshot **
sign-up

### CODE REVIEW

**Comment by Ananya9878** [comment]
@garg3133 Can you please review and close the PR.

**Review by garg3133 — COMMENTED** [review]
Hey @Ananya9878, first of all, really sorry for the delay. There was some emergency in my family.

Overall the method of implementation looks good and as expected. There are a few suggestions below which you should look into. 

Thanks for working on this issue.

**Comment by Ananya9878** [comment]
@garg3133 suggestions are implemented ...... pls review it again.

**Comment by garg3133** [comment]
Looks good @Ananya9878, merged into master 🎉 

Thank you for your contribution 🚀

**Pull request merged**
