### PR TITLE
forget password

### PR DESCRIPTION
**Pull request by kumarishalini6**
# Related Issue
Fixes: #264

# Prosposed Changes
- I have an svg image
- 
Jagrati _ Password Reset - Personal - Microsoft​ Edge 5_17_2021 07_58_05 AM

### CODE REVIEW

**Comment by AJAYSHARMA2012** [comment]
@kumarishalini6 it looks good but the page is not responsive anymore. You can use Bootstrap if you want.

**Comment by kumarishalini6** [comment]
Oo I am really very sorry I forgot to make it responsive I will make it

**Comment by kumarishalini6** [comment]
Now the Page is responsive
Jagrati _ Password Reset - Personal - Microsoft​ Edge 5_17_2021 03_28_12 PM
Jagrati _ Password Reset - Personal - Microsoft​ Edge 5_17_2021 03_28_39 PM

**Comment by kumarishalini6** [comment]
@AJAYSHARMA2012  why the checks are not visible?

**Comment by AJAYSHARMA2012** [comment]
Screenshot (609)
It is still not responsive. There should be a gap after the reset button on small screen devices and it should be properly indented.

**Comment by kumarishalini6** [comment]
ok let me fixed it

**Comment by kumarishalini6** [comment]
The gap in bottom is fine  at my laptop, but I have give some margin and I have also now form is properly indented
Jagrati _ Password Reset - Personal - Microsoft​ Edge 5_18_2021 01_59_23 PM

**Comment by AJAYSHARMA2012** [comment]
@kumarishalini6 It is still not working. You are adding too much explicit styling like padding, margin etc. Use bootstrap classes like justify-content-center, text-center, row, etc. It would make the things easy and looks good.

**Comment by kumarishalini6** [comment]
Now check it this time i only use bootstrap.

**Comment by AJAYSHARMA2012** [comment]
This looks fine @kumarishalini6. Great Work!! @garg3133 I have reviewed this PR. Please look into it.

**Review by AJAYSHARMA2012 — APPROVED** [review]

**Comment by kumarishalini6** [comment]
@garg3133  please review this PR the GSSoC'21 about to end.

**Comment by garg3133** [comment]
@kumarishalini6 Why have you changed the style of text-field and the button below? It looked really good. Now, it just looks a bit odd and too long.

Other problems I found in this PR:
* Footer is not visible on the page (please don't make any changes to footer, as it will affect all the pages on the whole app).
* There's no margin below the card, due to which the bottom of the card gets attached to the bottom of the page on small screens, which looks odd and the bottom shadow is also lost.
* There's too much gap between the SVG and the key icon for small screens, and the gap only increases on reducing the screen size.
  (Maybe we can just remove the SVG on small screens, as the reset password field should be visible on the first frame itself when the site is opened on small screens.)

You should test for different mobile devices as well whenever you're developing something, which can be done using the Chrome Developer tools.

**Comment by kumarishalini6** [comment]
Now check it , I have made all the changes that you have maintioned above.

**Comment by garg3133** [comment]
@kumarishalini6 You should not make any changes to `base.html`, `home/index.html` and `snippets/footer.html` as changes in these files will affect the whole app. Instead of adding CSS properties to `container` class (which you should never do as `container` is a Bootstrap class), you can just add a new class to that element and add properties to that class.

**Comment by kumarishalini6** [comment]
OK I'll do that  , any other changes ? , is everything alright?

**Comment by kumarishalini6** [comment]
Done

**Comment by garg3133** [comment]
> Now check it , I have made all the changes that you have mentioned above.

Let me test it by running on my local system.

> Done

Nope, I can still see the `base.html` and `home/index.html` files in this PR. These files should not be present in this PR.

**Comment by AJAYSHARMA2012** [comment]
@kumarishalini6 The page is not responsive for mobile devices. please do the suggested changes by @garg3133.

**Comment by garg3133** [comment]
* The reset password block should be vertically centred on small screens.
* You can just use the `d-md-flex` class to apply flex up to 768px and then return back to block.
* Do not use negative margins. Most of the times, the same effect can be achieved by reducing some positive margins/paddings.
* Increase the margins at the top as the screen size reduces, so that the card remains centred (You can do this my using breakpoints in Bootstrap classes for margins/padding). See the spacing section in https://www.w3schools.com/bootstrap4/bootstrap_utilities.asp.

**Comment by kumarishalini6** [comment]
ok I'll do that changes first I check the commit  i have simply copy the original code .

**Comment by kumarishalini6** [comment]
Can you please give me 2 days , because my internal is from today

**Comment by kumarishalini6** [comment]
I have tried but "d-md-flex" is not working , could you please help me

**Comment by garg3133** [comment]
> I have tried but "d-md-flex" is not working , could you please help me

Did you just use `d-md-flex` or `d-block d-md-flex`. You need to use the latter one. You can check the Bootstrap documentation on display for more details.

**Comment by garg3133** [comment]
Hey @kumarishalini6, while the current design also looks good (you are a really good UI designer), the page still has many problems:
* The SVG image remains at the top, while it should be centred vertically.
* The page breaks on small screens and looks really bad.
  image

While I would have loved to take this design forward, sadly I don't have much time to keep reviewing the PR. So, I'm thinking of sticking to the previous design, at it was almost complete and the remaining things are quite easy to fix.

Can you please just revert your last commit? Rest I will take care of. You just need to run 
```
git revert 6895488
```
in your terminal/git bash and then push the changes.

Thanks.

**Comment by kumarishalini6** [comment]
@garg3133 I am really very sorry but I am not able to do that change , I have not that much knowledge of bootstrap I hope you don't mind.

**Comment by garg3133** [comment]
Merged, after making the required changes in 6959be2.

Thanks, @kumarishalini6 for working on this.

**Pull request merged**
