### PR TITLE
update contributing.md

### PR DESCRIPTION
**Pull request by khareyash05**
With reference to issue #139 
update contributing.md added items as specified in the issue

Added the following -

1. Difference between GIT and GITHUB
2. How to clone,fork repository
3. How to create a branch and then use git push to push to repo
4. Create a PR
5. Squash commits in a single issue into one
6. Updating the forked and local repo as the updations are made in the upstream
@garg3133 Have a look!

### CODE REVIEW

**Comment by garg3133** [comment]
Thank you @khareyash05 for working on this but I feel that all this is very basic knowledge and not everyone reading the contributing guide would require this, so it unnecessarily increases the size of our contributing guide.

Instead of this, we can put all this in a separate file and add a link to that file in our contributing guide so that the size of our contributing guide remain small and those who need this getting started guide can access it through the link in our contributing guide.

**Comment by khareyash05** [comment]
Ok so i should create another file containing the same
Suggest me a name of that file. 
Guidelines.md?

**Comment by garg3133** [comment]
@khareyash05 github-guidelines.md maybe?

**Comment by khareyash05** [comment]
@garg3133 on it

**Comment by khareyash05** [comment]
Hi I am opening a a new pull request give me a few minutes

**Pull request closed without merging**
