### PR TITLE
Fixed the transitions

### PR DESCRIPTION
**Pull request by sparshsharma2510**
# Related Issue
Fixes: #281  

# Prosposed Changes
- change 1
- change 2
Now the card info and the header appear simultaneously on hovering over them.

# Additional Info
- any additional information or context
I have added an animation on the card which makes the transition smoother and well timed
# Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

### CODE REVIEW

**Comment by sparshsharma2510** [comment]
@garg3133 I have made the appropriate changes in the CSS file kindly review them.

**Comment by garg3133** [comment]
@sparshsharma2510 The same transition should also occur when the second card goes back again and the first card comes up.

**Comment by sparshsharma2510** [comment]
Hey, @garg3133 I just added a rollback transition to that information card kindly check it.

**Comment by garg3133** [comment]
Looks good now @sparshsharma2510. Merging it into master.

Thanks, for working on this.

**Pull request merged**
