### PR TITLE
Add Paytm Payment for Donation

### PR DESCRIPTION
**Pull request by ashutoshkrris**
# Related Issue
Fixes: #119

# Prosposed Changes
- Added Paytm Payment for Online Donations
- Added information about Paytm Keys/Tokens in README and .env.save

# Screenshots
Screenshot (286)
Screenshot (287)
Screenshot (288)
Screenshot (289)

### CODE REVIEW

**Comment by ashutoshkrris** [comment]
@garg3133 Please have a look

**Comment by garg3133** [comment]
@ashutoshkrris On the first look, your code mostly looks good and clean. I'll review it tomorrow.

Just one thing I don't like is the placement of "Donate Now" button. Yeah, I asked you to place it there but it looks odd due the the large difference in the height of the two columns. Any thoughts on better placement of button?

**Comment by ashutoshkrris** [comment]
Sorry @garg3133 
Since, I am mostly involved in Backend Dev, I won't be able to suggest any such.

**Comment by garg3133** [comment]
@ashutoshkrris Can you please redirect this PR to be merged in `paytm-integration` branch instead of the `master` branch. Actually, we don't have any plans to use this feature as of now in the application but I still wanted this option to be present in the web app so that whenever we need an integrated payment portal in the application, we won't have to spend much time in creating one.

Thank you so much @ashutoshkrris for working on this!

**Comment by ashutoshkrris** [comment]
yeah, sure @garg3133 !
no problem

**Comment by garg3133** [comment]
Merged! Thanks @ashutoshkrris!

**Pull request merged**
