### PR TITLE
UI changes to password_change_done.html

### PR DESCRIPTION
**Pull request by rray14**
# Prosposed Changes
- Changed UI of password_change_done.html

# Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:

image

image

### CODE REVIEW

**Comment by garg3133** [comment]
@rray14 Can you make this page look like https://jagrati.herokuapp.com/accounts/authenticated/? We want all our pages to be consistent in design and structure.

Also, it would be better if you use the existing code of the above-mentioned page and make changes in it, so that the design looks consistent and it does not create problem on different screen sizes.

For the home button, can you implement the design and text of the button as in #192?

**Comment by rray14** [comment]
Yes sure, I'll get that ready asap

**Comment by rray14** [comment]
Hey @garg3133 I've made the changes, is it fine?

**Comment by garg3133** [comment]
Merged! 🎉 

Thanks @rray14 for your contribution 🚀

**Pull request merged**
