### PR TITLE
HTML Validation

### PR DESCRIPTION
**Pull request by tanishq-arya**
# Related Issue
Fixes:   #221  

# Prosposed Changes
- Removed excess tags and outdated properties.
- Added alt tags to images

### CODE REVIEW

**Comment by garg3133** [comment]
Looks good, merged!

Thanks, @tanishq-arya for the contribution.

**Comment by tanishq-arya** [comment]
@garg3133 can the level be changed to 2. 1 is for documentation changes.

**Comment by garg3133** [comment]
@tanishq-arya That's not true. It is only suggested that Level0 can be given to small documentation issues and Level2 can be given to major documentation changes, but it's totally up to the project admin how he/she chooses to grade the participants. Like if someone put in a lot of efforts in improving the documentation of a project, it would be unfair to just label the PR as Level1.

I mark the levels based on the difficulty of the issue and the efforts put in by the contributor to resolve the issue. And as this was an easy issue, I marked it as Level1.

**Comment by tanishq-arya** [comment]
I thought it was fixed that level 0,1 for documentation only. My mistake.

**Pull request merged**
