### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by rohan8660**
Donation Section updated

### CODE REVIEW

**Comment by rohan8660** [comment]
Please check and suggest changes if any.😀

**Comment by tmo66** [comment]
Yeah, there are many

1. @garg3133  already written it several times, still, I'm writing that. 

> While working on an issue or implementing a new feature, always first create a new branch and then start working. Never make your changes directly onto the master branch as the master branch should always be clean and in sync with the original repository. This helps a lot if you accidentally mess things up or want to work on different issues at the same time.

2. Coming to the point, your sentence won't work, not at all, I'm writing some suggestions you can work upon, and will make some good changes
     a) Stick to the point.
     b) Use some catchy words/sentences with an affirmative tone.
     c) As Jagrati was totally related to Education, use this as your main tool.
     d) Read different donation lines from diff wev to get some idea on how to write it.
I am sure you will write some good line.

Waiting for a good PR :)

**Comment by rohan8660** [comment]
Thanks for noting down the points, I will work on those.

**Comment by rohan8660** [comment]
I have made a new branch and created a new pull request from there. #10

**Pull request closed without merging**
