### PR TITLE
Added Github Link

### PR DESCRIPTION
**Pull request by Aayush-hub**
Fixes: #103

### CODE REVIEW

**Comment by Aayush-hub** [comment]
@garg3133 Please review my PR under mexili and SWOC labels :)

**Comment by garg3133** [comment]
@Aayush-hub The changes you've made have messed up the colour of Youtube and GitHub icon on hover. Can you please check that?

Also. the GitHub icon should appear 350ms after the Youtube icon has appeared.

**Comment by Aayush-hub** [comment]
@garg3133 Done with the changes:)

**Comment by garg3133** [comment]
Looks good @Aayush-hub! Merged it into master.

Thanks for your contribution 🚀

**Pull request merged**
