### PR TITLE
Added django Forms for creating/updating of student

### PR DESCRIPTION
**Pull request by harshakhmk**
# Related Issue
Fixes: 
- Added Django forms to handle create / update of student and rendered Django forms in HTML code
- Created a form class to handle input data and for validation of fields

### CODE REVIEW

**Review by garg3133 — COMMENTED** [review]
@harshakhmk This is how the Add student and update student page are being displayed:

image

image

Didn't you test your changes before opening this PR? Please always test your changes thoroughly before opening a PR.

**Comment by harshakhmk** [comment]
Local host is not running on my PC, I will make the changes

**Comment by garg3133** [comment]
@harshakhmk What is the problem you're facing? Haven't you followed the setup procedure written in the Readme file?

**Comment by harshakhmk** [comment]
I have followed the exact same steps but loading ```http://127.0.0.1:8000/``` taking a lot of time

**Comment by garg3133** [comment]
That's weird! Is anything getting logged into the terminal while you wait for the home page to load?

**Comment by harshakhmk** [comment]
I have updated the latest commit I have tested for add new student ,update student it is working fine, 
Code is working, u can review it now

**Comment by garg3133** [comment]
@harshakhmk While the previously mentioned problem has been solved now, the implementation is for the most part incomplete. To point out a few things:
* We are using django forms now, but not really utilizing any features of Django forms. The field validation is Django default only, which should be sufficient in this case, but if the form is not valid, instead of showing the user what data was entered previously and showing the errors related to each field below it, it just shows the toast error message and resets the form, which can be quite frustrating as the user now don't know what he entered before and because of which field the error is occurring.
* The profile image in add_student form is not getting saved.
* On update profile also, we are not leveraging the form to display the data in the form.

See if you can fix these problems and implement the form in a better way, otherwise there is no use in moving to Django forms as of now if we cannot leverage it properly.

**Comment by harshakhmk** [comment]
For adding a new student, it shows exactly what fields  are invalid/missing and it stores previously entered values I have tested it

**Comment by garg3133** [comment]
> For adding a new student, it shows exactly what fields are invalid/missing and it stores previously entered values I have tested it

Haan, but that's the frontend implementation, done through Bootstrap and as it was pointed out in #280 that frontend can be manipulated with. But I guess, you are right. We don't need to send back the errors or previous data from the backend, as those who will be manipulating with the frontend would not be the legitimate users anyway. We just need to ensure that no incorrect data gets into our system if someone tries to manipulate with the frontend.

The main concerns with this are the other two points.

**Comment by harshakhmk** [comment]
> > For adding a new student, it shows exactly what fields are invalid/missing and it stores previously entered values I have tested it
> 
> Haan, but that's the frontend implementation, done through Bootstrap and as it was pointed out in #280 that frontend can be manipulated with. But I guess, you are right. We don't need to send back the errors or previous data from the backend, as those who will be manipulating with the frontend would not be the legitimate users anyway. We just need to ensure that no incorrect data gets into our system if someone tries to manipulate with the frontend.
> 
> The main concerns with this are the other two points.

I didn't get exactly get what you meant in point 3

**Comment by harshakhmk** [comment]
@priyansh3133  can you review it

**Comment by garg3133** [comment]
Merged, after making a few changes in update profile workflow.

**Comment by harshakhmk** [comment]
> Merged, after making a few changes in update profile workflow.

Thanks

**Comment by garg3133** [comment]
Yeah, sure.

**Pull request merged**
