### PR TITLE
Added Flake8 Linter

### LINKED ISSUE #97: A Linter for Python
As we are using Django as our backend, I believe it would be a good idea to have a Linter for Python.

This will help in enforcing guidelines, code quality, and documentation at the same time ensuring that no improper or vulnerable code has been pushed in the Repo.

### PR DESCRIPTION
**Pull request by vybhav72954**
I have added a Flake8 Linter, as proof of its working, I will allow it to run on the whole codebase once, there will be a to of errors (hopefully not) considering you told me that there is no strict guideline.

Fixes #97

After that I will ensure that it runs on new PRs only, I can also make it to run on the pushes also in case you want me to do that.

### CODE REVIEW

**Comment by vybhav72954** [comment]
The linter woked on whole [codebase](https://github.com/garg3133/JagratiWebApp/pull/104/checks?check_run_id=1888095595) before the lastest commit.

After - [here](https://github.com/garg3133/JagratiWebApp/pull/104/checks?check_run_id=1888266728) no file was checked as this PR contains no Python file.

Kindly tell me if I should leave this action for PRs only or pushes also?

**Comment by vybhav72954** [comment]
Fixes #97

**Comment by garg3133** [comment]
Having it run on pushes too would be better.

**Comment by garg3133** [comment]
Having it run on pushes too would be better.

**Comment by vybhav72954** [comment]
> Having it run on pushes too would be better.

Definitely, I will update that

**Comment by vybhav72954** [comment]
> Having it run on pushes too would be better.

Done

**Comment by garg3133** [comment]
LGTM! Merging this to master.

**Pull request merged**
