### PR TITLE
donation-modal enhanced #23

### PR DESCRIPTION
**Pull request by harikishantk**
I had updated the donation-modal with color gradients and changed some font face.

### CODE REVIEW

**Comment by tmo66** [comment]
@harikishantk please add Screenshot of Modal, through Screenshot it would be easier for us to review your PR.

**Comment by harikishantk** [comment]
> 
> 
> @harikishantk please add Screenshot of Modal, through Screenshot it would be easier for us to review your PR.

image

**Comment by garg3133** [comment]
@harikishantk It looks really great but it is a bit fancy for a social work website. Can you just maybe keep it a little simple (not as simple as the old one but also not as fancy as this one). Thanks!

**Comment by harikishantk** [comment]
> 
> 
> @harikishantk It looks really great but it is a bit fancy for a social work website. Can you just maybe keep it a little simple (not as simple as the old one but also not as fancy as this one). Thanks!

Yeah, it looks fancy, my bad and I was thinking about it while doing it. I'll make some changes and Thank you for your feedback and replying back.

**Pull request closed without merging**
