### PR TITLE
New Page: List of all Students added resolved conflicts

### PR DESCRIPTION
**Pull request by harikishantk**
https://github.com/garg3133/JagratiWebApp/pull/91#issue-568743286

### CODE REVIEW

**Comment by garg3133** [comment]
You pushed the `sample-db.sqlite3` file again. Also, a lot of packages are removed from requirements.txt.

**Comment by harikishantk** [comment]
I had installed `django-filter` package and the packages which is listed in `requirements.txt` as per in the `readme.md` of your repo. Do check out.

**Comment by garg3133** [comment]
You've entirely deleted the `sample-db.sqlite3` file while it was to be removed from the commit only. Also, I think `python-social-auth` package that you've added in `requirements.txt` is of no use for this PR.

Apart from this, after reviewing your changes...

For the frontend part:
* Students should be group in classes (heading of class and then cards of all the students of that card).
* Sort by asc/desc order should change the order of student cards per class (that is, you should not mix up the students of different classes). The students should be arranged in the asc/desc order of names per class.
* On selecting a value from dropdown menu (like sort in asc order), the value should remain selected in the dropdown after page refresh.
* Students must appear in asc order by default (which can be easily done in `index` function based view by using `students = Student.objects.order_by('school_class', 'first_name`, 'last_name`)`.
* On clicking on students cards, user must be redirected to their profile (which should open in a new tab).
* The design of filters don't match with the design of "Search name" field.
* Page is not responsive to screen size (it gets really weird on small screens).
* Don't use a separate version of Bootstrap for this particular page but use the version already being used on other pages. These frameworks should always be uniform for all over the application.

For backend part:
* You've created `StudentSerializer` but never used it.
* Search name can be easily implemented using plain javascript (see search field in student/volunteer attendance).


@harikishantk I personally feel that you are overkilling and overcomplicaing the task. All this task can be easily done by using just plain django along with AJAX and do not require any 3rd party packages. Like for the sorting of students, you can send an AJAX request to the backend, the backend will query the database for the data which you can order by using `order_by(school_class, first_name, last_name)` method (it will first order the data according to class and then for each class, it will order the data according to student name) and then send the data back to the browser and using the new data, you can update the page without the need of any page refresh. Using AJAX is really easy, you can see the other places AJAX has been used (by searching `$.ajax` globally for your reference.

And even for doing it without AJAX, you don't need any additional package like `django_filter` which is just over-complicating the code by adding so many extra class-based views and additional routes. You can solve this problem with just one funtion-based view by sending the arguments (class, asc/desc) as GET requests (like `http://localhost:8000/students?class=1&order=asc` for class 1 students in ascending order and just `http://localhost:8000/students` for students of all classes) and then querying the data on the backend and sorting it according to the arguments received and finally displaying it on the template.



On a side note, don't try to implement everything all at once but take one task and complete it then go to another. Like this particular task could be divided into many sub-tasks like first displaying all the students only without the option of filtering. Once that is done (like I said above, page should be responsive and cards should be clickable among other things), you can move to the filtering feature and so on. One more example can be like we know that using AJAX for filtering would be a better option as it does not require page refreshes but implementing it can be tough at the start, so you can first implement the filtering using the GET requests (like I explained above) and then once the feature works fine with GET requests, modify the app to use AJAX instead. You may even open a separate issue for each task and complete it as a separate PR (which will also give you extra points for all the hard work you've put into this PR :)).

Whlie contributing to Open Source, it is really important to do the tasks in small chunks so that it is easier for the maintainers to review your work and for you to make any changes according to the review. 


I hope you take this in a good spirit and as a positive feedback :)

**Comment by harikishantk** [comment]
I got confused up with so many features, yes as you said, I have to do in small chunks. Thank you for suggesting out so many things from it. I'll make the changes as you had commented out. 😄

**Comment by garg3133** [comment]
Students list was added in 2125eeb3. Thank you @harikishantk for your time and efforts in this. Closing this PR now.

**Pull request closed without merging**
